services:
  ajna-rfq:
    build: .
    restart: always
    image: ajna-rfq:latest
    ports:
      - "80:80"
    environment:
      PORT: 80
      CONFIG_FILE: /app/cfg/config.json
      DATABASE_FILE: /app/db/orders.db
    volumes:
      - /opt/ajna-rfq/cfg:/app/cfg
      - /opt/ajna-rfq/db:/app/db
